#!/usr/bin/env bash

#
# Alters Slack App package contents to include a style shee that is easier on the eyes
#


SOURCE_CSS_PATH=./css/black.css
ENTRYPOINT_PATH=/Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/ssb-interop.js
TARGET_CSS_PATH=/Applications/Slack.app/Contents/Resources/slack-darkmode.css

echo "Closing Slack..."
osascript -e 'quit app "Slack"'

echo "Copying dark theme CSS..."
cp $SOURCE_CSS_PATH $TARGET_CSS_PATH

if [[ ! -f "$ENTRYPOINT_PATH.orig" ]]; then
  echo "Making a backup of the entrypoint file..."
  cp "$ENTRYPOINT_PATH" "$ENTRYPOINT_PATH.orig"
fi

echo "Resetting entrypoint file..."
cp "$ENTRYPOINT_PATH.orig" "$ENTRYPOINT_PATH"

echo "Injecting dark theme entrypoint..."
read -r -d '' SNIPPET <<'EOF'

///////////////////////////////////////////////////////////////////////////////
//
// Injected by slack-darkmode script
// This snipped needs to be re-added everytime you update Slack
//

document.addEventListener('DOMContentLoaded', function() {
  let fs = require('fs');
  let filePath = '/Applications/Slack.app/Contents/Resources/slack-darkmode.css';
  let tt__customCss = `.menu ul li a:not(.inline_menu_link) {color: #fff !important;}`
  fs.readFile(filePath, {encoding: 'utf-8'}, function(err, css) {
    if (!err) {
      $("<style></style>").appendTo('head').html(css + tt__customCss);
      $("<style></style>").appendTo('head').html('#reply_container.upload_in_threads .inline_message_input_container {background: padding-box #545454}');
      $("<style></style>").appendTo('head').html('.p-channel_sidebar {background: #363636 !important}');
      $("<style></style>").appendTo('head').html('#client_body:not(.onboarding):not(.feature_global_nav_layout):before {background: inherit;}');
    }
  });
});
EOF
echo "$SNIPPET" >> $ENTRYPOINT_PATH
echo "Done! Re-opening slack!"
open -a Slack
