#!/usr/bin/env bash

#
# Alters Slack App package contents to include a style shee that is easier on the eyes
#

set -e

HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
APP_MACOS=/Applications/Slack.app/Contents/Resources
APP_LINUX=/usr/lib/slack/resources
if test -d $BASE_PATH_MACOS; then
  APP=$APP_MACOS
  OS="macos"
elif test -d $BASE_PATH_LINUX; then
  APP=$APP_LINUX
  OS="linux"
else
	echo "Can't find slack resource directory"
	exit 1
fi
CSS=slack-darkmode.css
ASAR=app.asar

# Ensure we're working with a clean bundle
if [[ ! -f "$APP/app.asar.orig" ]]; then
  echo "Making backup..."
  sudo cp -v $APP/$ASAR $APP/$ASAR.orig
else
  sudo cp -v $APP/$ASAR.orig $APP/$ASAR
fi

echo "Injecting dark theme entrypoint..."
sudo cp -v $HERE/$CSS $APP/$CSS
mkdir -p $HERE/tmp
asar extract $APP/$ASAR $HERE/tmp/$ASAR.tmp
tee -a $HERE/tmp/$ASAR.tmp/dist/ssb-interop.bundle.js <<-EOF
///////////////////////////////////////////////////////////////////////////////
//
// Injected by slack-darkmode script
// This snipped needs to be re-added everytime you update Slack
//
document.addEventListener('DOMContentLoaded', function() {
  require('fs').readFile('$APP/$CSS', {encoding: 'utf-8'}, function(err, css) {
    if (!err) {
      \$("<style></style>").appendTo('head').html(css);
    }
  });
});
EOF
asar pack tmp/$ASAR.tmp $HERE/tmp/$ASAR
sudo cp -v $HERE/tmp/$ASAR $APP/$ASAR

echo "Done! restarting slack!"
killall slack
if [ "$OS" = "macos" ]; then
  open -a Slack
elif ["$OS" = "linux" ]; then
  slack
fi
